### ISSUE TITLE
PointRCNN on dense 

### ISSUE THREAD

**Issue by barzanisar** [SysCV/LiDAR_snow_sim#10]
Hey Martin,

I am training pointrcnn on dense dataset clear weather split. However it breaks [here](https://github.com/MartinHahner/OpenPCDet/blob/main/pcdet/datasets/processor/data_processor.py#L171).

The problem is that the number of field of view points becomes less than half of 16384 (due to mask_points_and_boxes_outside_range function).
Note: 16384 is the number of points sampled for pointrcnn by "sample_points". 

For example: 
If after masking points outside range, the len(points) is 5000, then 
choice = np.arange(5000)
np.random.choice(, 16384-5000, replace=False) breaks because np.choice cannot sample number of points (i.e. 11384) larger than the number of points in choice (i.e. 5000) without replacing.

How did you manage to overcome this issue during training?

Thank you for the help!

**Comment by MartinHahner** [comment]
I did not encounter this particular issue.

It could be, that this error occurs because there are only a few bad frames in your training set. 
At one point, I excluded all the frames with less than 3000 points inside the camera field of view.
<img width="1211" alt="grafik" src="https://user-images.githubusercontent.com/14181188/178140894-99c2a1f3-6793-4176-9438-7bb28630d42d.png">

You can find those splits [here](https://github.com/MartinHahner/SeeingThroughFog/tree/8975764f369734978635f585eb12ee2a53c7d7d4/splits) and try using e.g. [train_clear_FOVstrongest3000.txt](https://github.com/MartinHahner/SeeingThroughFog/blob/8975764f369734978635f585eb12ee2a53c7d7d4/splits/train_clear_FOVstrongest3000.txt) instead.
